# are repairals enabled or not
enabled: true     

# Delay before the repair starts (in seconds)
delay: 1

# time between each block (in seconds)
repair-speed: 0.2

# activate/deactvate repairal based on the explosion type
explosion-types:
  creeper: true
  tnt: true
  ghast: true
  bed: true
  wither: true
  lightning: true
